# Generated by Django 6.1 on 2026-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(blank=True, to='store.category'),
        ),
    ]
